name = "backend-cloudflare"
main = "build/index.js"
compatibility_date = "2026-03-08"

[build]
command = "cargo install -q \"worker-build@^0.7\" && worker-build --release"

[[r2_buckets]]
binding = "mybucket"
bucket_name = "mybucket"

[[kv_namespaces]]
binding = "mykv"
id = "mykv"
