[package]
name = "backend"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
axum = { workspace = true, features = ["json"] }
tower-service = { workspace = true }
tracing = { workspace = true }
worker = { workspace = true, optional = true }
bindings = { path = "../bindings" }
models = { path = "../models" }

[features]
cloudflare = [ "worker" ]
